const nodemailer = require('nodemailer');

const createTransporter = () => {
  const { SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_SECURE } = process.env;

  if (!SMTP_HOST || !SMTP_USER || !SMTP_PASS) {
    throw new Error('Email service not configured. Check SMTP_HOST, SMTP_USER, SMTP_PASS.');
  }

  return nodemailer.createTransport({
    host: SMTP_HOST,
    port: parseInt(SMTP_PORT || '587'),
    secure: SMTP_SECURE === 'true',
    auth: { user: SMTP_USER, pass: SMTP_PASS },
    tls: { rejectUnauthorized: process.env.NODE_ENV === 'production' },
  });
};

const sendSummaryEmail = async (recipientEmail, summaryHtml, filename) => {
  const transporter = createTransporter();
  const senderName = process.env.EMAIL_FROM_NAME || 'Sales Insight Automator';
  const senderEmail = process.env.SMTP_USER;

  const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #f4f7fb; margin: 0; padding: 0; }
    .container { max-width: 680px; margin: 32px auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
    .header { background: linear-gradient(135deg, #0f172a 0%, #1e40af 100%); padding: 36px 40px; }
    .header h1 { color: #fff; margin: 0; font-size: 22px; font-weight: 600; letter-spacing: -0.3px; }
    .header p { color: #93c5fd; margin: 8px 0 0; font-size: 13px; }
    .badge { display: inline-block; background: rgba(255,255,255,0.15); color: #fff; padding: 3px 10px; border-radius: 20px; font-size: 11px; margin-top: 10px; }
    .content { padding: 36px 40px; color: #1e293b; line-height: 1.7; }
    .content h2 { color: #0f172a; font-size: 18px; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
    .content h3 { color: #1e40af; font-size: 15px; margin-top: 20px; }
    .content ul { padding-left: 20px; }
    .content li { margin-bottom: 6px; }
    .footer { background: #f8fafc; padding: 20px 40px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 12px; }
    strong { color: #0f172a; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📊 Sales Intelligence Report</h1>
      <p>AI-generated summary by Rabbitt AI</p>
      <span class="badge">📎 ${filename}</span>
    </div>
    <div class="content">
      ${summaryHtml}
    </div>
    <div class="footer">
      Generated by Sales Insight Automator · Rabbitt AI · ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}
      <br>This report was auto-generated by AI and should be reviewed before formal use.
    </div>
  </div>
</body>
</html>`;

  const info = await transporter.sendMail({
    from: `"${senderName}" <${senderEmail}>`,
    to: recipientEmail,
    subject: `📊 Sales Insight Report — ${filename} — ${new Date().toLocaleDateString()}`,
    html: htmlBody,
    text: summaryHtml.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim(),
  });

  return { messageId: info.messageId, accepted: info.accepted };
};

module.exports = { sendSummaryEmail };
